site_name: Hordekit
site_description: A comprehensive Python library for cryptographic algorithms and analysis tools
site_author: Илья Новак
site_url: https://anakilivo.github.io/hordekit/

repo_name: anakilivo/hordekit
repo_url: https://github.com/anakilivo/hordekit
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [hordekit]
          options:
            show_source: true
            show_root_heading: true

nav:
  - Home: index.md
  - Installation: installation.md
  - Quick Start: quickstart.md
  - Algorithms:
    - Symmetric:
      - Substitution Ciphers: 
        - crypto/symmetric/substitution/index.md
        - Caesar Cipher: crypto/symmetric/substitution/caesar.md
        - Affine Cipher: crypto/symmetric/substitution/affine.md
        - Atbash Cipher: crypto/symmetric/substitution/atbash.md
        - ROT13 Cipher: crypto/symmetric/substitution/rot13.md
        - ROT47 Cipher: crypto/symmetric/substitution/rot47.md
  - API Reference:
    - Crypto Utils: api/crypto_utils.md
    - Base Classes: api/base_classes.md
  - Development:
    - Contributing: development/contributing.md
    - Testing: development/testing.md

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - toc:
      permalink: true 